spring.application.name=financeiro

## --- JPA / Hibernate ---

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Thymeleaf ---

spring.thymeleaf.cache=false

# --- Servidor ---
# No Render a porta vem da variavel PORT (padrao 10000)

server.port=${PORT:8080}
server.address=0.0.0.0
