spring.application.name=financeiro
# --- Postgres local ---
spring.datasource.url=jdbc:postgresql://localhost:5432/financeiro
spring.datasource.username=sa
spring.datasource.password=Thagab02
spring.datasource.driver-class-name=org.postgresql.Driver